### ISSUE TITLE
Original bot is down / doesn't detect updates 

### ISSUE THREAD

**Issue by pikachu99** [Davoleo/curse-updates#21]
The curse bot isn't detecting new updates of modpacks. I am not sure if it just takes a while or if it is something else. 
also in order for the bot to post in a channel does it need permission?

**Comment by Davoleo** [comment]
Yeah the bot does need permissions to send messages in the annoucements channel for it to work;
that said, during this period the bot might be down or unresponsive because the old API is fairly unstable and I'm in the process of migrating it to the new API, if you need the bot features your best bet at the moment is to self-host it on your machine, otherwise the official version will be back working around the release of the next major version [(milestone here)](https://github.com/Davoleo/curse-updates/milestone/1).
